(SETQ TREE '(D D1 D2 D3 D4 D11 D12 D121)) 
(SETQ D '((NAME . "LISP")(P . 1)(UP)(DOWN D1 D2 D3 D4)))
(SETQ D1 '((NAME . "Listy") (P . 0.45)(UP . D)(DOWN D11 D12))) 
(SETQ D2 '((NAME . "Tablice")(P . 0.2)(UP . D) (DOWN)))
(SETQ D3 '((NAME . "Liczby")(P . 0.2)(UP . D) (DOWN)))
(SETQ D4 '((NAME . "Stringi")(P . 0.15)(UP . D) (DOWN)))
(SETQ D11 '((NAME . "Proste operacje na listach")(P . 0.65)(UP . D1) (DOWN)))
(SETQ D12 '((NAME . "Listy asocjacyjne")(P . 0.35)(UP . D1) (DOWN . D121))) 
(SETQ D121 '((NAME . "Przebudowywanie list")(P . 1.0)(UP . D12) (DOWN)))
